Feature/fetch article data
theKono/KPS-iOS pull request #42
Opened 2022-05-31 05:51 UTC by angelcic

2022-05-31 05:58 UTC, mingshing commented on KPS/Networking/CoreAPIService.swift
> +        case .fetchArticle(_, _, _, let server):
寫法保持一致比較好~ (case要一個一個拆開寫，或是合再一起

2022-05-31 06:01 UTC, mingshing commented on KPSTests/Article/KPSClientArticleTests.swift
> +                XCTAssertTrue(articleContent.isFree)
articleContent 裡可以access到的property，都要檢查是不是有parse正確

2022-05-31 06:04 UTC, mingshing commented on KPSTests/Article/KPSClientArticleTests.swift
> +    func testFetchArticleContentSuccess() {
還要補上 
成功的時候要分有permission時的response，跟沒有permission的response是不是都能正確handle
帶錯的articleId，有沒有辦法正確handle
沒有網路的時候，有沒有辦法正確handle

2022-05-31 06:05 UTC, mingshing requested changes
test可以再多補一些~
CoreAPIService 要不要改就隨意

2022-05-31 07:45 UTC, angelcic commented on KPS/Networking/CoreAPIService.swift
> +        case .fetchArticle(_, _, _, let server):
現在拆開是因爲目前可以拿到 article content 的 project id 跟 GBI 不同，開發中暫時先分開比較好切換 project id，不然應該寫一起就好了？

2022-07-03 07:43 UTC, mingshing commented on KPSTests/Article/KPSClientArticleTests.swift
> +                XCTAssertEqual(error.errorDescription, "The operation couldn’t be completed. (NSURLErrorDomain error -1009.)")
這我覺得不用加，一個是因為我們沒有來這個description來用
另外一個是如果apple換了description，那unit test會壞掉，

2022-07-03 07:53 UTC, mingshing commented on KPSTests/Article/KPSClientArticleTests.swift
> +        let customFailedEndpointClosure = { (target: CoreAPIService) -> Endpoint in
這兩個4xx 的mock endpoint，也一樣包個function去生成
這樣看test的時候，就可以看到code大概是寫 stubbingProvider = MoyaProvider<CoreAPIService>(endpointClosure: customFailedEndpointClosure(withStatusCode: 4xx), stubClosure: MoyaProvider.immediatelyStub)

2022-07-03 08:07 UTC, mingshing commented on KPS/Model/KPSArticle.swift
> +    enum infoContainerKeys: String, CodingKey {
這邊幾個coding key，看要不要KPSArticle, KPSAudio 能共用的都整理出來寫到另外一個地方
backend那邊應該都是當KPS的一個file type，大部份的key應該是可以共用的
另外命名的大小寫方式儘量保持同一種rule，像這邊ContentDataKeys,  infoContainerKeys，第一個字要不要大寫就可以統一一下

2022-07-03 08:24 UTC, mingshing commented on KPSTests/Article/KPSClientArticleTests.swift
> +                XCTAssertEqual(articleContent.error, .needLogin)
這個test好像沒有跑道success來
可以在下面的default 加上 XCTAssert(false)，確定有跑到該跑的地方

2022-07-03 08:28 UTC, mingshing commented on KPS/Model/KPSPDFContent.swift
> +    enum CodingKeys: String, CodingKey {
json data -> model，如果沒有要多做額外的處裡，可以不用再定義CodingKeys，跟public init(from decoder: Decoder)

2022-07-03 08:32 UTC, mingshing requested changes
testFetchArticleContentWithoutPermission
這個test看一下，好像sample data沒有正確被parse，但test 還是success
parser跟test都要改一下

其他的comment都是建議~  可改可不改

2022-07-06 06:41 UTC, angelcic commented on KPS/Model/KPSArticle.swift
> +    enum infoContainerKeys: String, CodingKey {
這個我再想想要怎麼改

2022-07-07 01:31 UTC, mingshing approved these changes

2022-07-07 01:32 UTC, mingshing commented
看起來可以merge囉~
順便再發一版到cocoapod上

2022-07-10 03:33 UTC, merged